wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718627840
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 13
      - 16
      - 23
      - 24
      - 61
      4: 3.10.14
      5: 0.17.1
      8:
      - 5
      - 9
      13: linux-x86_64
